apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    application: spring-boot-simple-server
    template: basic-spring-boot
  name: spring-boot-simple-server
spec:
  tags:
    - annotations:
        tags: spring-boot-simple-server
      from:
        kind: DockerImage
        name: fuse7/spring-boot-simple-server:latest
      name: latest
      referencePolicy:
        type: Local